package com.ks.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.ks.entity.OrderDetail;
import com.ks.entity.OrderDetailKey;

public interface OrderDetailMapper extends BaseMapper<OrderDetail> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int deleteByPrimaryKey(OrderDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    OrderDetail selectByPrimaryKey(OrderDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int updateByPrimaryKey(OrderDetail record);
}
