package com.ks.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.ks.entity.AdminInfo;
import com.ks.entity.ProductType;

public interface ProductTypeMapper extends BaseMapper<ProductType> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int insert(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int insertSelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    ProductType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int updateByPrimaryKeySelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int updateByPrimaryKey(ProductType record);
}
