package com.ks.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.ks.entity.ProductInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ProductInfoMapper extends BaseMapper<ProductInfo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int deleteByPrimaryKey(ProductInfo key);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int insertSelective(ProductInfo record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int updateByPrimaryKeySelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    int updateByPrimaryKey(ProductInfo record);
}
