package com.ks.entity;

import java.io.Serializable;
import java.util.Date;

public class FunctionMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_menu.id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_menu.parent_id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_menu.fc_name
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private String fcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_menu.fc_url
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private String fcUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_menu.status
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_menu.seq
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_menu.create_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_menu.update_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table function_menu
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_menu.id
     *
     * @return the value of function_menu.id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_menu.id
     *
     * @param id the value for function_menu.id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_menu.parent_id
     *
     * @return the value of function_menu.parent_id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_menu.parent_id
     *
     * @param parentId the value for function_menu.parent_id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_menu.fc_name
     *
     * @return the value of function_menu.fc_name
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public String getFcName() {
        return fcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_menu.fc_name
     *
     * @param fcName the value for function_menu.fc_name
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setFcName(String fcName) {
        this.fcName = fcName == null ? null : fcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_menu.fc_url
     *
     * @return the value of function_menu.fc_url
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public String getFcUrl() {
        return fcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_menu.fc_url
     *
     * @param fcUrl the value for function_menu.fc_url
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setFcUrl(String fcUrl) {
        this.fcUrl = fcUrl == null ? null : fcUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_menu.status
     *
     * @return the value of function_menu.status
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_menu.status
     *
     * @param status the value for function_menu.status
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_menu.seq
     *
     * @return the value of function_menu.seq
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_menu.seq
     *
     * @param seq the value for function_menu.seq
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_menu.create_time
     *
     * @return the value of function_menu.create_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_menu.create_time
     *
     * @param createTime the value for function_menu.create_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_menu.update_time
     *
     * @return the value of function_menu.update_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_menu.update_time
     *
     * @param updateTime the value for function_menu.update_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}