package com.ks.entity;

import java.io.Serializable;

public class OrderDetailKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.oid
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.pid
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.id
     *
     * @return the value of order_detail.id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.id
     *
     * @param id the value for order_detail.id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.oid
     *
     * @return the value of order_detail.oid
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.oid
     *
     * @param oid the value for order_detail.oid
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.pid
     *
     * @return the value of order_detail.pid
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.pid
     *
     * @param pid the value for order_detail.pid
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}