package com.ks.entity;

import java.io.Serializable;
import java.util.Date;

public class ProductType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.type_name
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.create_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.update_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_type
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.id
     *
     * @return the value of product_type.id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.id
     *
     * @param id the value for product_type.id
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.type_name
     *
     * @return the value of product_type.type_name
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.type_name
     *
     * @param typeName the value for product_type.type_name
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.create_time
     *
     * @return the value of product_type.create_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.create_time
     *
     * @param createTime the value for product_type.create_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.update_time
     *
     * @return the value of product_type.update_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.update_time
     *
     * @param updateTime the value for product_type.update_time
     *
     * @mbg.generated Sun Dec 18 09:32:51 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}